scan_url_invalidate: 你扫码的网址错误！
auto_reply_not_support_your_message: 自动回复暂时无法处理您的消息
auto_reply_not_support_this_type: 自动回复暂时不支持这种类型的消息
scan_item_has_used: 红包已领取过，不能重复领取！
scan_item_redpacket_exceed_total: 用户领取的红包个数超过了限制，不能领取啦！
scan_item_redpacket_exceed_daily: 用户领取的红包个数超过当天领取的上限，请明天再来扫面分享
scan_item_city_not_match: 此产品的红包仅在指定城市有效！
scan_item_user_not_found: 用户不存在，请确定已经关注公众号！
scan_item_not_found: 你扫码的产品不存在！
scan_item_not_enable: 你扫码的产品现金红包未启用！
scan_item_redpacket_got: 红包领取成功
