server.port: 8080
spring.profiles: default
demo.security.jwt:
  tokenExpirationTime: 150 # Number of minutes
  refreshTokenExpTime: 600 # Minutes
  tokenIssuer: http://svlada.com
  tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus

spring.datasource:
  url: "jdbc:mysql://localhost/redpacket?useUnicode=true&characterEncoding=utf-8"
  driverClassName: com.mysql.jdbc.Driver
  username: root
  password: ""
  data: "classpath*:data.sql"
  sql-script-encoding: utf-8
spring.jpa:
  hibernate:
    ddl-auto: create
  show-sql: true

  
#spring.datasource:
#  url: "jdbc:h2:mem:testdb"
#  driverClassName: org.h2.Driver
#  username: sa
#  password: ""
#  data: "classpath*:data.sql"
#spring.jpa:
#  database-platform: org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled: true