server.port: 8080
spring.profiles: default
demo.security.jwt:
  # Number of minutes
  tokenExpirationTime: 150 
  refreshTokenExpTime: 600
  tokenIssuer: http://svlada.com
  tokenSigningKey: xm8EV6Hy5RMFK4EEACIDAwQus

spring.datasource:
  url: "jdbc:mysql://localhost:3306/redpacket?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci&characterSetResults=UTF-8"
  driverClassName: com.mysql.jdbc.Driver
  username: root
  password: ""
  data: "classpath*:data.sql"
  sql-script-encoding: utf-8
spring.jpa:
  hibernate:
    ddl-auto: create
  show-sql: true
  # https://github.com/spring-projects/spring-boot/issues/2763
  # http://stackoverflow.com/questions/32437202/improvednamingstrategy-no-longer-working-in-hibernate-5
#  properties:
#    hibernate.implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
#    hibernate.physical_naming_strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#    hibernate.ejb.naming_strategy_delegator: ""
  

  
#spring.datasource:
#  url: "jdbc:h2:mem:testdb"
#  driverClassName: org.h2.Driver
#  username: sa
#  password: ""
#  data: "classpath*:data.sql"
#spring.jpa:
#  database-platform: org.hibernate.dialect.H2Dialect
#spring.h2.console.enabled: true


#wechat:
#  mp:
#    appId: wxf596e31049113e14
#    secret: 5e85ca80b40567cdc105299c08f45df7
#    token: test
#    aesKey: f7GgZCfK8o5bQVE9Hs3BHLP51SG2rD5wgXQ8LyDAbly
    
wechat:
  mp:
    appId: wx3909fcd001df528d
    secret: a1e229be117b2a8d45e4a48d4239d6ac
    token: test
    aesKey: f7GgZCfK8o5bQVE9Hs3BHLP51SG2rD5wgXQ8LyDAbly

app:
  mapKey: SP2BZ-B7MWJ-KW5F7-FVV37-S4UCO-XFFW6
  hostIpAddress: 202.203.208.20

